[package]
name = "tempconvert"
version = "0.1.0"
edition = "2021"
description = "package to convert temperature into different units, and their types"
license="MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
